//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace whnotify {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("whnotify.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Configure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigLang {
            get {
                return ResourceManager.GetString("ConfigLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigLangEnglish {
            get {
                return ResourceManager.GetString("ConfigLangEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigLangJapanese {
            get {
                return ResourceManager.GetString("ConfigLangJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logging に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigLog {
            get {
                return ResourceManager.GetString("ConfigLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigLogPath {
            get {
                return ResourceManager.GetString("ConfigLogPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigNotify {
            get {
                return ResourceManager.GetString("ConfigNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify sample に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigNotifySample {
            get {
                return ResourceManager.GetString("ConfigNotifySample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigServer {
            get {
                return ResourceManager.GetString("ConfigServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP Address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigServerIpaddress {
            get {
                return ResourceManager.GetString("ConfigServerIpaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NIC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigServerNic {
            get {
                return ResourceManager.GetString("ConfigServerNic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigServerPort {
            get {
                return ResourceManager.GetString("ConfigServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Service に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ServiceStart {
            get {
                return ResourceManager.GetString("ServiceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ServiceStop {
            get {
                return ResourceManager.GetString("ServiceStop", resourceCulture);
            }
        }
    }
}
